# Generated by Django 3.0.7 on 2020-06-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='file_image')),
                ('judul', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
