# Generated by Django 3.0.7 on 2020-06-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kategori',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='file_image/sampul_buku'),
        ),
    ]
