# Generated by Django 3.0.7 on 2020-06-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200613_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='penulis',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
